name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} / Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go-version:
          - "1.23.x"
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Vet
        run: make vet

      - name: Test
        run: make test

  verify:
    name: linux / verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Check
        run: make check

      - name: Examples
        run: make examples

      - name: Staticcheck
        run: make staticcheck

      - name: Vulnerability Check
        run: make vulncheck

      - name: Distcheck
        run: make distcheck

      - name: Race
        run: make test-race
