name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - "INTEGRATION.md"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: docs

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@d8af841ac341d06640cbe393899ae55e59e77c00
